maxdron123/band_4_rent

app/models/band.rb
app/models/user.rb
app/views/bands/index.html.erb
app/views/bands/show.html.erb
db/migrate/20230730211942_change_members_count_data_type.rb
db/schema.rb

- added a list of 4 bands
- coded the index and show html.erb

bands_view

---

app/controllers/application_controller.rb
app/controllers/bands_controller.rb
app/controllers/checkouts_controller.rb
app/controllers/pages_controller.rb
app/models/band.rb
app/models/checkout.rb
app/models/user.rb
app/views/bands/edit.html.erb
app/views/bands/new.html.erb
app/views/devise/registrations/new.html.erb
app/views/layouts/application.html.erb
config/routes.rb
db/migrate/20230730211942_create_checkouts.rb
db/migrate/20230730211943_change_column_types_in_bands.rb
db/migrate/20230730211944_add_name_to_users.rb
db/schema.rb
test/controllers/checkouts_controller_test.rb
test/models/checkout_test.rb

1.Created Checkout MVC
2.Created New view for band with form and connected it to a Create action
3.New band is created with logged in user_id
4.Removed authenticaton check for homepage and /about, all other pages ask to log in or sign up
5.Changed members_count column to integer and description column to text in bands table
6.Implemented #set_bands method in bands controller
7.Created Edit band view with form and connected it to Update
8.Added presence validation for name, genre, members_count, description and rate fee and connected references between other models
9.Added first_name and last_name to user registration form
10. After logging in, Message now shows "Hi, user.first_name"(needs to be moved to an index page)
I need the index and show to make checkout view

Implemented checkout and more stuff

---

app/controllers/pages_controller.rb
app/views/pages/about.html.erb

Hey everyone, I edited the about method as well as the the corresponding html file by defining some instance variables and displaying them in the view. I have no idea if it works cause I can't log in past the local servers sign in page but let me know what you think.

about method and about html erb

---

app/assets/stylesheets/components/_band_container.scss
app/assets/stylesheets/components/_index.scss
app/views/bands/index.html.erb
app/views/bands/show.html.erb

1. Created a _band_container.scss component to add CSS styling                                                                                   2. Imported the custom CSS component to _index.scss              3. Added the new class container to index.html.erb and show.html.erb                                                                             4. Made the text <strong> to add more visual appeal

Index-Show

---

.gitignore
Gemfile
Gemfile.lock
app/assets/stylesheets/application.scss
app/assets/stylesheets/components/_avatar.scss
app/assets/stylesheets/components/_card.scss
app/assets/stylesheets/components/_navbar.scss
app/controllers/application_controller.rb
app/controllers/bands_controller.rb
app/models/band.rb
app/models/user.rb
app/views/bands/my_bands.html.erb
app/views/bands/new.html.erb
app/views/bands/show.html.erb
app/views/devise/registrations/new.html.erb
app/views/shared/_navbar.html.erb
config/environments/development.rb
config/routes.rb
config/storage.yml
db/migrate/20230730211946_create_active_storage_tables.active_storage.rb
db/schema.rb

Made a new action #my_bands with a view, so logged in user can see his created bands
customized my bands view with flex bootstrap
Added link to My Bands in navbar dropdown( click on avatar -> My bands)
Expanded the navbar and changed background to test picture
Customized website logo and placed it on the left side of the banner. on hover and click, sends to a home page
Implemented Cloudinary:
1.User can upload his photo upon registration, it will be shown on the right side of the navbar. If not uploaded, default icon will be shown
2.User can apply multiple pictures when creating a band, they will be shown in show page
3.On My bands page first image of the band is shown
4.If user didn't attach photos of the band, empty picture icon is shown.
Maybe there is something more, you can check it …

Added many stuff

---

app/assets/stylesheets/components/_card.scss
app/controllers/pages_controller.rb
app/views/bands/my_bands.html.erb
app/views/pages/home.html.erb

1. Edited cards format to be equal size.
2. Homepage showing latest bands added to app. New band will be first. Later needs to be restricted to a fixed number of bands shown OR put into carousel

Customized homepage and edited cards

---

app/views/bands/edit.html.erb
app/views/bands/index.html.erb
db/schema.rb

I tried to do the design you created on Figma, feel free to change anything you don't like

allbands-frontend

---

app/views/bands/index.html.erb
db/schema.rb

- Made some modifications CSS style.

Index_page

---

app/views/bands/show.html.erb

I centered all the details of the band and added a carousel for the photos, attaching a photo, adding a reviewer

customized bandshowpage

---

app/assets/stylesheets/application.scss
app/assets/stylesheets/components/_card.scss
app/assets/stylesheets/pages/_home.scss
app/views/bands/index.html.erb
app/views/pages/home.html.erb
app/views/shared/_navbar.html.erb
db/seeds.rb

1. Added background to app
2. styled and fixed previous commits

added backgrounds and made some fixes

---

app/views/bands/show.html.erb
app/views/layouts/application.html.erb
app/views/shared/_footer.html.erb
app/views/shared/_navbar.html.erb
db/seeds.rb

- Created the footer with some links to navigate
- Navbar bg looks a little better now
- Tried fixing the carousel and now works better but still have some issues which I'll think on how to solve but feel free to remove it if you wish

somechanges

---

.gitignore
app/assets/stylesheets/components/_card.scss
app/views/bands/index.html.erb
app/views/bands/my_bands.html.erb
app/views/bands/show.html.erb
app/views/pages/home.html.erb

^Copy link into google search bar without brackets
1. Created a custom card-img class in the card component.scss
2. Implemented img-fluid bootstrap to make it reactive
3. Implemented card-img class to all images to maintain aspect ratio
4. Added style parameters for home.html.erb + index.html.erb to ensure the image does not interfere with the card sizes and keeps them uniform

card-images

---

Gemfile
Gemfile.lock
app/controllers/application_controller.rb
app/controllers/bands_controller.rb
app/policies/application_policy.rb
app/policies/band_policy.rb
app/views/bands/show.html.erb
config/environments/development.rb
test/policies/band_policy_test.rb

Fixed devise - now unregistered users can see index page.
Added some restrictions:
1. Unregistered user can see only index page, home page and about page
2. The buttons "Edit" and "Delete" on the show page are now visible only for users who created this bands

pundit implemented

---

Gemfile
Gemfile.lock
app/assets/stylesheets/components/_footer.scss
app/controllers/bands_controller.rb
app/models/band.rb
app/views/bands/index.html.erb

- Added the search bar on the index page, did not add it to the navbar because the form takes a path and it may vary depending on the page one is on and I am not sure how to add multiple paths to the form.

added search bar

---

app/assets/stylesheets/application.scss
app/assets/stylesheets/components/_card.scss
app/views/bands/index.html.erb
app/views/shared/_footer.html.erb
db/seeds.rb

- Added new font
- Adde star icon on index page

Fontawesome

---

db/seeds.rb

- 4 new fictional bands
- 2 new users

AdditionalBands

---

app/assets/stylesheets/pages/_index.scss
app/assets/stylesheets/pages/_my_checkouts.scss
app/assets/stylesheets/pages/_show.scss
app/controllers/bands_controller.rb
app/controllers/checkouts_controller.rb
app/controllers/pages_controller.rb
app/javascript/application.js
app/javascript/controllers/application.js
app/javascript/controllers/checkout_controller.js
app/javascript/controllers/controller_controller.js
app/javascript/controllers/index.js
app/models/checkout.rb
app/policies/band_policy.rb
app/policies/checkout_policy.rb
app/policies/page_policy.rb
app/views/bands/show.html.erb
app/views/checkouts/_form.html.erb
app/views/pages/my_checkouts.html.erb
app/views/shared/_navbar.html.erb
config/routes.rb
db/migrate/20230730211942_create_checkouts.rb
db/schema.rb
test/policies/checkout_policy_test.rb
test/policies/page_policy_test.rb

added show.scss in assets/pages to customize show page
moved button "All bands" on the show page
fixed authorization bugs
Checkout is now working:
1.User can rent a band on a desired date with the button on the show page
2.If the date is correct, user is redirected on the homepage and sees a notification
3.User cannot rent same band twice as long as his checkout exists
4.In avatar dropdown list there is a "My rents" link to the corresponding page
5.In my-checkouts page, band's names lead to the corresponding show page
6.Renting date cannot be from the past(validation)

Features and fixes

---

app/assets/stylesheets/components/_card.scss
app/views/bands/index.html.erb
app/views/bands/my_bands.html.erb
app/views/bands/show.html.erb
app/views/checkouts/_form.html.erb
app/views/layouts/application.html.erb
app/views/pages/home.html.erb
app/views/shared/_footer.html.erb

updated as per branch title

---

app/views/bands/index.html.erb
app/views/bands/my_bands.html.erb
app/views/pages/home.html.erb

1. Re-implemented "Band 4 Rent" Homepage title, Latest added bands, and Browse all bands button
2. Made it so there are borders between the card images and cards for respective home + index + my band .html.erb pages 
3. Aligned the band name and band description texts 
4. Aligned images within the card

new_images

---

app/assets/stylesheets/application.scss
app/views/bands/index.html.erb
app/views/bands/show.html.erb
app/views/pages/home.html.erb
db/seeds.rb

- New font
- New font icon musical note
- Added extended text description

NewChanges

---

app/assets/stylesheets/components/_navbar.scss
app/assets/stylesheets/pages/_index.scss
app/assets/stylesheets/pages/_my_notifications.scss
app/controllers/pages_controller.rb
app/helpers/spinner_helper.rb
app/javascript/controllers/checkout_controller.js
app/javascript/controllers/controller_controller.js
app/javascript/controllers/index.js
app/javascript/controllers/notification_controller.js
app/models/band.rb
app/models/user.rb
app/policies/page_policy.rb
app/views/bands/show.html.erb
app/views/pages/my_notifications.html.erb
app/views/shared/_navbar.html.erb
app/views/shared/_notification.html.erb
app/views/shared/_spinner.html.erb
config/routes.rb

added dependence on destroy user -> bands, user -> checkouts and band->checkouts
added validation of band description - minimum 20 characters
fixed renting - the user now cannot rent the band he created
"Messages" in navbar changed to "Notification":
1.if current user's band is rented, he will recieve notification from there
2.Click to see notification notice
3.Click again to hide it
4.Added spinner when band is rented
Added My-notifications page

Finished with checkout
